### PR TITLE
#145: Migrate to JUnit 5.

### PR DESCRIPTION
**Pull request by Wandmalfarbe**
Should close issue #145.

- Migrated from JUnit `4.12` to JUnit `5.5.2` (Jupiter).
- Use JUnit exception handling instead of `BaseTest#getException()`
- Updated the Gradle version from `3.5-rc-2-all` to `6.0.1-bin`. Starting with version 4.6, Gradle provides native support for executing tests on the JUnit Platform.
- Fixed Maven warnings for plugins without a version number.
- Fixed Maven warning about platform dependent file encoding.

### CODE REVIEW

**Comment by romankh3** [comment]
Thanks for your contribution, @Wandmalfarbe !
Something went wrong with your updates, as you can see, checks have not completed yet.
It must be fixed.

Best regards,
 Roman.

**Comment by Wandmalfarbe** [comment]
I can submit a new pull request if it helps?

**Comment by romankh3** [comment]
Yes, you can. Add a new commit with updates in your repository - it will automatically update this PR.

**Comment by Wandmalfarbe** [comment]
I feel like this won't work. Maybe try that:
- https://github.community/t5/GitHub-Actions/GitHub-Actions-Pull-requests-always-include-some-outdated-checks/td-p/30030
- https://github.com/travis-ci/travis-ci/issues/10204

**Comment by romankh3** [comment]
I created a new Pull-Request to check. Removed codacy and coveralls checks. Nevertheless build and security is not working here... I don't know why.

**Comment by romankh3** [comment]
@Wandmalfarbe thanks for your contributions.
I'll take care of all the checks, later.

**Comment by Wandmalfarbe** [comment]
Glad I could help!

**Pull request merged**
