### PR TITLE
Allow program to run as a traditional CLI

### PR DESCRIPTION
**Pull request by renatoathaydes**
In this PR, I 've added a simple `ArgsParser` class to allow user to pass in options to the program, so that they can compare two images from image files they pass in as arguments.
The user can also give a file where the result should be saved to. Not providing an output file makes the program open the UI, as it does currently.

I also made the jar created by Gradle be runnable (by adding the `Main-Class` entry to the manifest), so now you can run the program with `java -jar image-comparison.jar`.

### CODE REVIEW

**Comment by renatoathaydes** [comment]
That coverage decrease is pretty weird, given that almost the only thing I changed in `ImageComparison`, the class which accounts for all of the decrease, was the `main` function and new constructor! Not sure what kind of test would be useful for that!

**Comment by renatoathaydes** [comment]
The Coveralls report was green when I commented!! Looks like it changed later.
The `main` function is not testable unless you actually run the java process and capture the output to see if it's as expected, or use some UI testing tool that can detect the image displayed in the UI, both of which are massive overkill for those few lines of code in `main`!
I will break up main into smaller methods and try to test those... but if you don't mind me saying, this is waste of time, the project tests are quite adequate in my opinion...
I will add something on the README page.

**Comment by renatoathaydes** [comment]
Looks like coveralls is happy now.
@romankh3  Can you publish this on Maven Central/JCenter?

If you need any help I can make a Pull Request with the necessary changes.
Here's a guide if you want to do that: https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/

**Comment by romankh3** [comment]
You've done good work. I will accept your changes and merge it into `master` branch.

**Comment by romankh3** [comment]
@renatoathaydes, I don't have enough time to do that and don't have an experience in publishing to Maven Central. 
Please, provide pull-request with required changes.

**Comment by renatoathaydes** [comment]
Thanks.

>  Please, provide pull-request with required changes.

Sure, but first you'll have to get a Sonatype account and Bintray account. The link I gave above explain how you do that.

**Comment by romankh3** [comment]
@renatoathaydes Hello. I did something, but I'm not sure that it's what you want. I added a barge to README.md and you can see it.

Please, provide some feedback. 

P.S. I wrote you an email message.

**Pull request merged**
